---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: exampleSite/content/code
  label: Code
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/page
  label: Page
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/link
  label: Link
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/audio
  label: Audio
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/video
  label: Video
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/gallery
  label: Gallery
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/article
  label: Article
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/quote
  label: Quote
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content
  label: Pages
  create: all
  match: "*"
upload_dir: exampleSite/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.48'
